- README.md
This pull request fixes a minor issue in the `README`: It's missing a step to create the `docker/lib/ext` directory, which doesn't exist in a fresh copy of the repo.
I also corrected two minor typos and removed some trailing whitespace.
> Add a missing step to the README

- docker/etc/webdefault.xml
Changes to docker/etc/webdefault.xml to use correct JspServlet class, and to correct the security-constraints for disabling TRACE method. These changes need to be applied to all other webdefault.xml instances used by gae/gcloud.
> Issue 32 and Issue 34

- appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/runtime/jetty9/SessionManager.java
- appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/runtime/jetty9/SessionManagerTest.java
The Session.renewId(Request) method has been implemented for appengine compat sessions. This makes the Request.changeSessionId() method now work for appengine.
The only piece missing is the automatic changing of session id when a user authenticates - not sure that is appropriate as appengine does not use sessions as part of the authentication mechanism.
> Implement changing session id

- gce-debian-openjdk/pom.xml
- gce-debian-openjdk/src/main/docker/Dockerfile
This allows downstream images to just use CMD to run vanilla Java code.
Alternatively, they can override ENTRYPOINT to automatically run framework code.
> Set ENTRYPOINT to execute java.

- README.md
Fix for issue #79. One possible suggestion to keep README working is just to suggest the script.
> Update README To Just use buildimage script

- gce-debian-openjdk/src/main/docker/Dockerfile
Undoing the change to set the default ENTRYPOINT.
Leaving both ENTRYPOINT and CMD unset to match Docker's OpenJDK image.
> Do not set the ENTRYPOINT for docker image

- appengine-jetty-managed-runtime/src/main/docker/Dockerfile
- appengine-jetty-managed-runtime/src/main/docker/jetty_run.sh
- gce-debian-openjdk/pom.xml
- gce-debian-openjdk/src/main/docker/Dockerfile
- gce-debian-openjdk/src/main/docker/alpn/format-env-appengine-vm.sh
- gce-jetty/src/main/docker/Dockerfile
- gce-jetty/src/main/docker/docker-entrypoint.bash
- gce-jetty/src/main/docker/gce-alpn.mod
Issue #82
Moved gdbg, gprof and alpn to /opt
Added /opt/alpn/format-env-appengine-vm.sh create ALPN java args
Added $JETTY_BASE/modules/gce-alpn.mod to avoid downloading jetty ALPN
The env variable ALPN_ENABLE and ALPN_DISABLE follow the same pattern as
used for cdbg and cprof.
If ALPN_ENABLE is set, then the jetty_run.sh and docker-entrypoint.bash scripts
will call /opt/alpn/format-env-appengine-vm.sh.   That script will look for
ALPN_DISABLE and if not set, will produce arguments for the boot classpath.
> Added ALPN support to gce-debian-openjdk #82

- gke-debian-openjdk/src/main/docker/Dockerfile
- gke-debian-openjdk/src/main/docker/docker-entrypoint.bash
- gke-debian-openjdk/src/main/docker/gke-env.bash
- gke-jetty/src/main/docker/Dockerfile
- gke-jetty/src/main/docker/docker-entrypoint.bash
This entry point can run java commands and derived images need only set the CMD.
If this is acceptable, we can look are removing the near duplicate in gke-jetty
> Cloud Debugger/Profiler Entry point #117

- appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeTestBase.java
- gke-debian-openjdk/src/main/docker/Dockerfile
For issue #115  
The debs required turned out to be: 
```
ADD http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.2_1.0.2d-3_amd64.deb /tmp/
ADD http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-3_amd64.deb /tmp/
```
> Upgraded to openssl 1.02

- appengine-jetty-managed-runtime/src/main/docker/jetty_run.sh
- gke-debian-openjdk/README.md
- gke-debian-openjdk/src/main/docker/docker-entrypoint.bash
- gke-debian-openjdk/src/main/docker/gke-env.bash
- gke-jetty/README.md
- gke-jetty/src/main/docker/docker-entrypoint.bash
Improve the documentation in the README for the GKE images.
This also contains comments and simplifications in the entry point slips.. which detected a bug in that the gke_env.sh script had not been fully updated for the /opt home for cdbg and cprof
> improve README for gke images

- gke-debian-openjdk/src/main/docker/Dockerfile
Temporary fix for #143 to update to latest libssl version.   But issue should be left open until a durable store for the debs is found/created
> #143 Updated libssl dependency

- appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
- appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/utils/config/AppEngineWebXmlProcessor.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmRuntimeLogHandler.java
Backport fix from async-support for #136 and #124 
Update System property handling so that logging config is not masked.
Update JettyRunner to set the system property.
> Fix logging for #136

- jetty9-compat-base/src/main/jetty-base/etc/gae.xml
Fixed incorrect log path.
The testwebapp starts within the image now (using the testMetadataServer)
> Fixed incorrect log path #140

- openjdk8/src/main/docker/Dockerfile
- openjdk8/src/main/docker/sid.list
- Fix for the constantly changing libssl reference.
Will temporarily install the (sid) apt repository,
then install libssl1.0.2 and openssl only,
removing the sid repository afterwords.
This is a speculative fix, and if you follow the build you'll see that it only adds those dependencies, but it somehow feels dirty to do it this way.
> Issue #143 - Use (sid) to obtain libssl & openssl

- appengine-jetty-managed-runtime/src/main/docker/webapps/root.xml
Fix for  #186. root.xml was referring to etc/webdefault.xml in jetty.home instead of jetty.base.
> Fix #186 to use correct webdefault.xml

- jetty9/README.md
- openjdk8/README.md
- openjdk8/src/main/docker/setup-env.bash
The Cloud Debugger team confirmed that the Debugger issue that forced us to disable it temporarily on the flex env (including Phython runtimes) has been resolved. The team asked me to take an action to enable it. Note that the Debugger is already enabled by default on the standard env (including jetty9-compat), and it should be automatically enabled for Java flex as documented [here](https://cloud.google.com/debugger/docs/setting-up-java-on-app-engine).
I took the liberty to make a change to setup-env.bash at my discretion, but feel free to jump in.
The document [here](https://cloud.google.com/appengine/docs/flexible/java/dev-jetty9?hl=pt-BR#environment_variables) should also be revised to correct the explanation for the DBG_ENALBE env variable.
> Enable Cloud (Stackdriver) Debugger on Java flex by default

- jetty9/src/main/docker/Dockerfile
Following the discussion in #211, we make Jetty explode `root.war` into `$JETTY_BASE/webapps/root-exploded` in a proper way.
> Explode WAR into $JETTY_BASE/webapps/root

- gke-debian-openjdk/src/main/docker/Dockerfile
- gke-debian-openjdk/src/main/docker/gke-env.bash
- gke-jetty/src/main/docker/Dockerfile
- gke-jetty/src/main/docker/docker-entrypoint.bash
The previous PR had two problems:
1) Mysteriously, `webapps/root` is still empty (despite its timestamp is changed from 1970/01/01), which only happens in production but not in a local env.
2) Unpacked contents of `root.war` should be present **before** Jetty starts. If Jetty explodes `root.war` while it is being initialized, Stackdriver Debugger can't load the class and lib files of `root.war`.
So, I suggest the following changes that explicitly unpack `root.war`, as an ultimate solution. It works on my local machine and my own ad-hoc testing in production.
What this PR does:
- Revert the last Pull Requst that creates and touches `webapps/root`. (No need to create the directory since `unzip` will create it anyway.)
- Install `unzip`.
- Unpack `root.war` explicitly if present.
- Set …
> Explicitly unpack root.war (if present) into webapps/root

- appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateTest.java
Configure the logger during the unit tests so that unless debug has been requested, the expected stack traces are suppressed.
> suppress expected stack traces during unit testing

- openjdk8/src/main/docker/setup-env.bash
Internal bug: 28192592
Do not enable Stackdriver Debugger for local runs.
Please sync this with the master branch too.
> Disable Stackdriver Debugger when running locally

- appengine-managed-runtime/src/main/java/com/google/apphosting/utils/config/AppEngineWebXmlProcessor.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/utils/config/XmlUtils.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/utils/config/AppEngineWebXmlProcessorTest.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/utils/config/AppEngineWebXmlReaderTest.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/utils/config/AppEngineWebXmlTest.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/utils/config/XmlUtilsTest.java
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/AutoIdPolicy_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/ClassLoaderConfig_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/Empty_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/Minimal_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/NoThreadsafe_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/UrlStreamHandler_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/Valid_appengine-web.xml
- appengine-managed-runtime/src/test/resources/com/google/apphosting/utils/config/appengine-web.xsd
Also removes a [near] duplicated method (`getBody`) in favor of `getText` in `XmlUtils`.
Note that `getText` will concatenate the text content of children nodes, whereas getBody did not.  As this method is only called by code that seeks the text of a node with no (non-comment) children, this shouldn't be a problem.
> Ignore comments between XML tags and add XML parsing tests.

- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmRuntimeFileLogHandler.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateTest.java
- jetty9-compat-base/pom.xml
- jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/AppengineApiConfiguration.java
- jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
- jetty9-compat-base/src/main/jetty-base/webapps/root.xml
- jetty9-compat-base/src/test/java/com/google/apphosting/runtime/jetty9/SessionManagerIT.java
- jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java
- jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkIT.java
- pom.xml
- testwebapp/src/main/webapp/jstl.jsp
Handles #259 bu creating AppengineApiConfiguration to manage the classpath that is exposed and/or protected from the webapplication.    If the GAE API is not available in the webapp, then a warning is logged and the API is added to the classpath.
Currently javax.activation and javax.mail are treated as shared classes and the containers version is made available. If these are not listed, then even if they are in the added API jar, errors occur, which needs to be investigated.
Currently a specific list of org.apache packages are hidden.   A better approach may be to hide all org.apache classes and selectively reveals those needed for JSP, JSTL and EL support?
> Issue #259 Hide GAE API from webapp classpath

- jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/AppengineApiConfiguration.java
This commit reverts to the classloading visibility prior to #259, but maintains the AppengineApiConfiguration class as a better way to implement any classloader policy.
> Issue #259 revert to prior class visibility, but with updated mechanism

- jetty9-base/src/main/jetty-base/etc/gae.xml
- jetty9-base/src/main/jetty-base/modules/gae.mod
- jetty9-compat-base/src/main/jetty-base/etc/gae.xml
- jetty9-compat-base/src/main/jetty-base/modules/gae.mod
Temporary fix for #302 until parameter added to jetty release
> Configurable stop time #302

- gke-jetty/README.md
We should use `gcloud app` instead of `gcloud preview app` which will go away soon.
> Use `gcloud app` instead of `gcloud preview app`

- jetty9-base/pom.xml
- jetty9-base/src/main/jetty-base/etc/gae-web.xml
- jetty9-base/src/main/jetty-base/etc/gae.xml
- jetty9-base/src/main/jetty-base/modules/gae.mod
- jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
- jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkIT.java
- testwebapp/src/main/webapp/app.yaml
Hide app.yaml #306
For the pure jetty image, a deployment binding is used to apply a `gae-web.xml` (name needs to be changed when other `gae` names are changed) file to every context deployed.
For compat, the protectedTarget is just directly set.
> Hide app.yaml #306

- appengine-managed-runtime/pom.xml
- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java
- appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateTest.java
- jetty9-compat-base/pom.xml
Re-creating the PR from a local branch.
I added a small fix to the pom to make the image include jetty-client.jar.
@olamy
> Jetty http client async support

- appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
- appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/CommitDelayingOutputStream.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/CommitDelayingResponse.java
- gke-debian-openjdk/src/main/docker/Dockerfile
Set the response buffer size to the max response size.
This PR also updates the debian image to be setup the same as https://github.com/GoogleCloudPlatform/openjdk-runtime, including using openjdk-8.   This was done because the non-durable debian repositories have changed and it is not possible to build the previous image as it was.   Use of java-8 was chosen because java-7 is end-of-life and the source/target of the `maven-compiler-plugin` was already set the 1.8 in the pom!
> Fix big file handling

- appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
- appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java
- appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/CommitDelayingResponse.java
This PR rolls back the change in #349 which apparently causes very high memory use in the JVM.
Instead, this PR enables handling of large responses by just warning about the possibility of log messages being lost.
You might see messages like these in the logs.
```
com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext doScope: Response for request to '/big.jsp' was already committed (code=200). This might result in lost log messages.' 
com.google.apphosting.vmruntime.VmAppLogsWriter waitForCurrentFlush: End of request or previous flush has not yet completed, blocking.
```
However, the responses should not be truncated.
> Remove overwrite of response buffer size and just warn on committed response

- appengine-jetty-managed-runtime/src/main/docker/etc/webdefault.xml
Fix 307 error with deferred task on Flex compat by removing security constraint for deferred task, which isn't useful due to lack of user service and returns wrong errors to customers.
This is is isolated to deferred tasks. It is safe as a header (X-AppEngine-QueueName) is verified by DeferredTaskServlet before executing the task - this is a trusted header that can only be set by internal Google traffic.
Tested with a Flex app that enqueues and executes deferred tasks.
> Fix 307 error with deferred task on Flex compat
