appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettySessionTest.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeTestBase.java, testwebapp/src/main/webapp/WEB-INF/sessions-disabled-appengine-web.xml, testwebapp/src/main/webapp/WEB-INF/sessions-enabled-appengine-web.xml
Make the appengine-web.xml used by the tests configurable, and create variants with sessions enabled and disabled. Remove duplicate tests.
=> Fix session tests

appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettySessionTest.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeTestBase.java, testwebapp/src/main/webapp/WEB-INF/sessions-disabled-appengine-web.xml, testwebapp/src/main/webapp/WEB-INF/sessions-enabled-appengine-web.xml
Fixed the (non)ssl tests. Branched off the fix for the session tests.
=> Fix ssl tests

appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java
Use the jsp ServletContainerInitializer to configure the jsp engine for unit tests.
=> Configure setup for jsp engine for tests

.gitignore, README.md
syncing jetty93 from master in anticipation of switching master to jetty-9.3
=> Update Jetty93 from master 

appengine-jetty-managed-runtime/pom.xml, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyAuthTest.java, appengine-managed-runtime/pom.xml, appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmRequestUtils.java, gce-jetty/pom.xml, pom.xml, testwebapp/pom.xml
Cleaned up poms to clearly use java 1.8
Use 127.0.0.2 as force remote IP, which is known to be untrusted.
=> Fixed #78 and #73

appengine-java-logging/pom.xml, appengine-java-logging/src/main/java/com/google/apphosting/logging/JsonFormatter.java, appengine-java-logging/src/main/java/com/google/apphosting/logging/LogContext.java, appengine-java-logging/src/test/java/com/google/apphosting/logging/JsonFormatterTest.java, pom.xml
Add a separate logging module - main runtime will be updated to use it in a separate PR.
=> Add a separate module for AppEngine logging

appengine-java-logging/pom.xml, appengine-jetty-managed-runtime/pom.xml, appengine-jetty-managed-runtime/src/main/docker/Dockerfile, appengine-managed-runtime/pom.xml, gce-debian-openjdk/pom.xml, gce-jetty/pom.xml, pom.xml, testwebapp/pom.xml
Name all the modules and define dependencies between them.
Build each docker iamge in the package phase and add tags in each module.
=> Build cleanup.

gce-debian-openjdk/src/main/docker/Dockerfile
Re-added wget to base image for cloud debugger #96
=> Added wget to base image for #96

appengine-jetty-managed-runtime/src/main/docker/jetty_run.sh, gce-debian-openjdk/src/main/docker/Dockerfile, gce-jetty/src/main/docker/docker-entrypoint.bash
Following advice for work around for cloud debugger from #96
=> Download gcloud debugger from known public location #96

appengine-java-logging/pom.xml, appengine-jetty-managed-runtime/pom.xml, appengine-managed-runtime/pom.xml, circle.yml, gce-debian-openjdk/pom.xml, gce-jetty/pom.xml, pom.xml, testwebapp/pom.xml
Speculative PR to see if circleci will see the circle.yml for #106
=> Fixes for circleci for #106

appengine-jetty-managed-runtime/pom.xml, appengine-jetty-managed-runtime/src/main/docker/Dockerfile, circle.yml, gce-debian-openjdk/pom.xml, gce-jetty/pom.xml
Added docker removeImage clean targets for 
Also templated the handling of the jetty version in the Dockerfile as a slight cleanup for #102
=> Clean docker images #102

appengine-java-logging/pom.xml, appengine-jetty-managed-runtime/pom.xml, appengine-jetty-managed-runtime/src/main/docker/webapps/root.xml, appengine-managed-runtime/pom.xml
Use maven copy dependency plugin for #98
This is the same as #100 except rebased on latest master and from a branch so that discussion can take place during other development.
=> Use maven copy dependency plugin for #98

gce-debian-openjdk/src/main/docker/Dockerfile
Following advice from circleci
=> Untar with --no-same-owner for circleci #106

appengine-java-logging/pom.xml, appengine-jetty-managed-runtime/pom.xml, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java, appengine-managed-runtime/pom.xml, appengine-managed-runtime/src/main/java/com/google/apphosting/utils/servlet/VmHealthServlet.java, appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java, appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateTest.java, gke-debian-openjdk/pom.xml, gke-jetty/pom.xml, pom.xml, testwebapp/pom.xml
Update to 1.9.27 libraries and naming.
=> Internal sync up from our code.

appengine-jetty-managed-runtime/src/main/docker/Dockerfile, gke-debian-openjdk/src/main/docker/docker-entrypoint.bash, gke-jetty/src/main/docker/docker-entrypoint.bash
=> JAVA_OPTS applied last #131

openjdk8/src/main/docker/Dockerfile
do an upgrade and autoremove to make the image clean for #154
=> PR Issue 154

.gitignore
Adding / cleaning up the various patterns in your .gitignore to be more useful in the general sense.
=> Cleaning up .gitignore

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java, appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyEnvironment.java, circle.yml, jetty9/pom.xml
Work around for issue #164 by editing the generated URLs.   Tested against guestbook stage 3
=> Issue #164

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmRuntimeUtils.java
Bug https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/189
=> Apis usage using the new environment.

jetty9-compat/src/main/docker/jetty_run.sh, pom.xml
=> Issue #202

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyEnvironment.java, jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
This is not yet ready to merge as it needs testing.  PR created now to facilitate discussion on #201
=> Issue #201 User request ticket instead of global ticket before commit

jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java
=> Fixed #217 NPE

gke-debian-openjdk/README.md, gke-debian-openjdk/src/main/docker/gke-env.bash, gke-jetty/README.md
Do the same thing in #219 for the master branch.
=> Enable Stackdriver Debugger by default

gke-jetty/src/main/docker/Dockerfile
Doing the same thing in #213 on the master branch.
=> Explode WAR into $JETTY_BASE/webapps/root

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java, jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/AppEngineAuthentication.java
Reduced the verbosity of logs in VmApiProxyDelegate for #242
Also reviewed log levels in AppEngineAuthentication (and fixed some javadoc errors).
=> Issue #242 Less verbose logging

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyEnvironment.java, appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmMetadataCache.java, jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeInterceptor.java, jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java, jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java, jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContextTest.java, jetty9-compat-base/src/test/resources/webapp/WEB-INF/appengine-web.xml, jetty9-compat-base/src/test/resources/webapp/WEB-INF/logging.properties, jetty9-compat-base/src/test/resources/webapp/WEB-INF/web.xml
Take 2 at fixing #230 
Always use the request ticket unless ENV variable GAE_USE_GLOBAL_TICKET is set, in which case the global ticket is always used.
=> Issue #230 Always use global or request ticket

appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateTest.java, jetty9-compat/pom.xml, jetty9-compat/src/main/docker/Dockerfile, jetty9/src/main/docker/Dockerfile, openjdk8/pom.xml, openjdk8/src/main/docker/Dockerfile
Set env vars to identify image #207
=> Env Vars to identify image #207

openjdk8/src/main/docker/setup-env.bash
It seems a good idea to reset DBG_AGENT like ALPN_BOOT and SET_TMP.
=> Reset DBG_AGENT first as before

appengine-jetty-managed-runtime/src/main/docker/etc/gae.xml, appengine-jetty-managed-runtime/src/main/docker/modules/gae.mod
Temporary work around for #302 until property is available from jetty.
=> Longer jetty stop time #302

jetty9-compat/src/main/docker/Dockerfile
Issue #302, exec jetty_cmd.sh so that signals are passed to JVM
=> Issue #302, exec jetty_cmd.sh so that signals are passed to JVM

appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java, appengine-jetty-managed-runtime/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkTest.java, testwebapp/src/main/webapp/app.yaml
=> Hide app.yaml #306

gke-debian-openjdk/src/main/docker/Dockerfile
=> Switch base image from qa debian to debian8

gke-debian-openjdk/pom.xml
=> Pull latest debian8 image on build

gke-debian-openjdk/pom.xml
=> Disable cache for building openjdk8 image

appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmRequestThreadFactory.java
Removed mutex from VmRequestThreadFactory
=> Issue #331

README.md
=> Update readme with links to new repos

README.md, appengine-managed-runtime/pom.xml, jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeJettyKitchenSinkIT.java, jetty9/README.md, openjdk8/src/main/docker/Dockerfile, pom.xml
This is a merge of master to the async-support branch to keep the branch point up to date.
Most of the changes were not appropriate, but I believe these ones should be merged over.
=> Async support merge

appengine-managed-runtime/pom.xml, appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java, appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/AbstractVmApiProxyDelegateTest.java, appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateHttpCallTest.java, appengine-managed-runtime/src/test/java/com/google/apphosting/vmruntime/VmApiProxyDelegateMockTest.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> add unit test using embedded Jetty to test real http call

jetty9-compat-base/src/main/java/com/google/apphosting/runtime/jetty9/DeploymentCheck.java, jetty9-compat-base/src/main/jetty-base/etc/gae.xml, jetty9-compat-base/src/main/jetty-base/webapps/root.xml
Added deployment check for started connectors and an available context
=> Async support deploycheck

appengine-java-logging/pom.xml, appengine-managed-runtime/pom.xml, jetty9-base/pom.xml, jetty9-base/src/main/java/com/google/apphosting/jetty9/GoogleRequestCustomizer.java, jetty9-compat-base/pom.xml, jetty9-compat/pom.xml, jetty9/pom.xml, openjdk8/pom.xml, openjdk8/src/main/docker/Dockerfile, pom.xml, testwebapp/pom.xml
Same as #346 but for the async-support branch.
=> Add support X-Forwarded-Proto HTTP header for secure request detection [async-support]

README.md
Document how to update `jetty_cmd.sh` file after changing jetty configuration
=> Update README to note how to customize Jetty
